### ISSUE TITLE
Replaced file contains CRLF on Windows

### ISSUE THREAD

**Issue by oliversalzburg** [mohebifar/lebab#177] opened 2016-09-06 11:13 UTC
When I replace a file, it will be written with CRLF line endings on Windows. This is annoying in itself but especially noteworthy because the source file has LF line endings.

**Comment by nene** [comment] 2016-09-06 12:36
This is caused by issue https://github.com/benjamn/recast/issues/269 in Recast library. There's PR to fix it https://github.com/benjamn/recast/pull/311 but unfortunately there hasn't been any discussion around it. Perhaps @benjamn is away somewhere as there hasn't been any activity in Recast repo for a while.

There's also still a PR open in Lebab #172, but it doesn't really fix the root of the problem.

**Comment by oliversalzburg** [comment] 2016-09-06 12:41
Yeah, I came across those after posting this ticket. Very disappointing :(

**Comment by oliversalzburg** [comment] 2016-09-06 12:59
Maybe this approach is acceptable :P

**Comment by nene** [comment] 2016-09-06 14:06
Thanks for the patch, but I'd really would like to avoid adding a command line option. Instead I think we should run a simple auto-detection:

- if the original code contains `\r\n` use that, otherwise default to `\n` as the safe choice.

Also, there's no need to account for the historical `\r` - I'd like to first see an actual bug report from person who's using old Mac OS and has managed to get NodeJS running on it :)

I was hoping for this issue to be resolved in Recast, but I guess it won't happen quite so soon, so better to roll our own fix in the mean time. I'll take a look at implementing this - should be pretty simple really.

Also, thanks for pointing out the problem with running tests on windows.

**Comment by oliversalzburg** [comment] 2016-09-06 14:33
@nene Sounds great as well :)

**Closed** 2016-09-06 19:48 UTC

**Comment by nene** [comment] 2016-09-06 19:50
Pushed a fix and released it in 2.3.3. See if this solves your issue.

**Comment by oliversalzburg** [comment] 2016-09-06 20:08
Awesome. Will test this in the morning :)

**Comment by oliversalzburg** [comment] 2016-09-07 08:47
Working great :)

Now if only indentation (tabs vs spaces) would be correctly detected... ;D

**Comment by nene** [comment] 2016-09-07 11:02
Ah... I had not realized that Recast also won't preserve tabs.

Created a separate issue to tackle this: #179 
And also an issue for tests under windows: #180
